default-resources:
  - disk_mb=1024000
  - mem_mb=32096
  - time=120
  - gpus=0
rerun-incomplete: True
rerun-triggers: mtime
restart-times: 2
printshellcmds: True
reason: True
use-conda: True
use-singularity: False
show-failed-logs: True
